update to docker

diff --git a/apis/brand_api/Dockerfile b/apis/brand_api/Dockerfile
--- a/apis/brand_api/Dockerfile
+++ b/apis/brand_api/Dockerfile
@@ -1,33 +1,45 @@
-FROM python:3.11-slim as base
+FROM python:3.11-slim as build
 
 # define variable. Only usable during building, not when start execution.
-ARG PROJECT=apis/brand_api
+ENV PIP_DEFAULT_TIMEOUT=100 \
+    # Allow statements and log messages to immediately appear
+    PYTHONUNBUFFERED=1 \
+    # disable a pip version check to reduce run-time & log-spam
+    PIP_DISABLE_PIP_VERSION_CHECK=1 \
+    # cache is useless in docker image, so disable to reduce image size
+    PIP_NO_CACHE_DIR=1 \
+    POETRY_VERSION=1.3.2 \
+    PROJECT=apis/brand_api
+
+# this will be the working directory
+WORKDIR /home/user
+# copy files needed for poetry install
+COPY pyproject.toml poetry.lock ./alembic.ini ./
+
+RUN pip install "poetry==$POETRY_VERSION" \
+    && poetry install --no-root --no-ansi --no-interaction \
+    && poetry export --with dev -f requirements.txt -o requirements.txt
+
+FROM python:3.11-slim as base
 
 # this will be the working directory
 WORKDIR /home/user
 
-# If this is set to a non-empty string, Python won’t try to write .pyc files on the import of source modules.
-ENV PYTHONDONTWRITEBYTECODE 1
+COPY --from=build /home/user/requirements.txt .
 
-# If this is set to a non-empty string, force the stdout and stderr streams to be unbuffered.
-# This option has no effect on the stdin stream.
-ENV PYTHONUNBUFFERED 1
-
-# Confirm if pip is updated
-RUN pip install --upgrade pip
-
-# Install Poetry.
-RUN --mount=type=cache,target=/root/.cache pip install poetry==1.3.1
-
-# set environment variables for poetry
-ENV PATH="/home/user/.local/bin:/home/user/.venv/bin:${PATH}"
-ENV POETRY_NO_INTERACTION=1
-ENV POETRY_VIRTUALENVS_IN_PROJECT=true
-
-# copy files needed for poetry install, and run it
-COPY ./pyproject.toml ./alembic.ini ./
-RUN  --mount=type=cache,target=/root/.cache poetry install
-
+RUN set -ex \
+    # Create a non-root user
+    && addgroup --system --gid 1001 appgroup \
+    && adduser --system --uid 1001 --gid 1001 --no-create-home appuser \
+    # Upgrade the package index and install security upgrades
+    && apt-get update \
+    && apt-get upgrade -y \
+    # Install dependencies
+    && pip install -r requirements.txt \
+    # Clean up
+    && apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -rf /var/lib/apt/lists/*
 
 #
 # dev target
@@ -51,20 +63,15 @@ COPY ./$PROJECT /home/user/$PROJECT
 # start app with uvicorn
 CMD ["uvicorn", "apis.brand_api.main:app", "--log-config", "apis/brand_api/utils/log.ini", "--host", "0.0.0.0", "--port", "80"]
 
+USER appuser
+
 #
 # test target
 #
 FROM base as test
 
-# install dev dependecies with poetry
-RUN --mount=type=cache,target=/root/.cache poetry install --with dev
-
 # copy project
 COPY ./$PROJECT /home/user/$PROJECT
-
-# Creates the directory for the default location where mypy stores incremental cache info.
-RUN mkdir /home/user/.mypy_cache
-
 
 #
 # Default target.
